name: Build Nguyen Phu Mod Zalo Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: |
          DEVELOPER_DIR=$(xcode-select -p)
          echo "DEVELOPER_DIR=$DEVELOPER_DIR" >> $GITHUB_ENV

      - name: Compile Dylib
        run: |
          SDKPATH=$(xcrun --sdk iphoneos --show-sdk-path)
          clang -dynamiclib \
            -fobjc-arc \
            -arch arm64 \
            -miphoneos-version-min=14.0 \
            -isysroot "$SDKPATH" \
            -framework UIKit \
            -framework Foundation \
            -framework QuartzCore \
            -framework CoreGraphics \
            -w \
            NguyenPhuZaloMod.m -o NguyenPhuZaloMod.dylib

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NguyenPhuZaloMod-Dylib
          path: NguyenPhuZaloMod.dylib
