name: Build Nguyen Phu Mod Zalo Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download iPhoneOS SDK
        run: |
          git clone --depth 1 https://github.com/theos/sdks.git $HOME/sdks

      - name: Compile Dylib
        run: |
          xcrun -sdk macosx clang -dynamiclib \
            -fobjc-arc \
            -arch arm64 \
            -miphoneos-version-min=14.0 \
            -isysroot $HOME/sdks/iPhoneOS14.5.sdk \
            -framework UIKit \
            -framework Foundation \
            -framework QuartzCore \
            -framework CoreGraphics \
            -w \
            NguyenPhuZaloMod.m -o NguyenPhuZaloMod.dylib

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NguyenPhuZaloMod-Dylib
          path: NguyenPhuZaloMod.dylib
